name: Build PTCGLDeckTracker DLL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Project_Path: PTCGLDeckTracker/PTCGLDeckTracker.csproj
      # Path to the game installation so the build can locate the DLLs.
      # Customize for your own machine or CI environment.
      PTCGL_PATH: C:\\PTCGL\\Pokemon Trading Card Game Live

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build DLL
      run: dotnet build ${{ env.Project_Path }} -c Release -p:PTCGL_PATH="${{ env.PTCGL_PATH }}"

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: PTCGLDeckTracker.dll
        path: PTCGLDeckTracker/bin/Release/net8.0/PTCGLDeckTracker.dll
